{% set name = "TheanoLM" %}
{% set version = "1.3.1" %}
{% set sha256 = "398c949544bf93a3a7aa0440922b1b1e5287a89c658c93afb0570f902e4edfad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<34]
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - theano
    - h5py

test:
  imports:
    - theanolm
    - theanolm.commands
    - theanolm.network
    - theanolm.parsing
    - theanolm.scoring
    - theanolm.training
    - theanolm.vocabulary
  commands:
    - theanolm --help

about:
  home: https://github.com/senarvi/theanolm
  license: Apache 2.0 
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Recurrent neural network language modeling tool implemented using Theano'
  description: |
    TheanoLM is a recurrent neural network language modeling
    toolkit implemented using Theano. Theano allows the user
    to customize and extend the neural network very
    conveniently, still generating highly efficient code
    that can utilize multiple GPUs or CPUs for parallel
    computation. TheanoLM allows the user to specify
    arbitrary network architecture. New layer types and
    optimization methods can be easily implemented.
  doc_url: http://theanolm.readthedocs.org/
  dev_url: https://github.com/senarvi/theanolm

extra:
  recipe-maintainers:
    - psmit
    - senarvi
