travis:
  secure:
    BINSTAR_TOKEN: PS1icYj+aXTjKFKY5C12gvdqVCR7fBpUHZXG+HoXAwPUEPyFjWM+UNlBTMm+be3jQ7DbnP5Xc+Tpc5z0n754mWhg5T3irICkF4Cuibgfmn8N9K3u82YsaAWG4+8ixVQ54nRaAYsWdNUs9+nYDoi/qZHrKCe3Cai6DO5XqQRkkA0u497NRia+B+FbUdTJ/QtKvrtJM3i9uWvl+sXAfPOLLjrxRbtZ2keMCynPYQDOmWg4f62O4NERU1LkmVdBJyuSSayQUTwqPJvJE9o9DRqE0vW+LP5uff/PP8AfzA1BgD8dn7ClKr6sIUB8Ba7wcFb3sX7nGCV8DhAZrvD4yOAPaG9y1EesRCxIVRqpSppAUbm6tgSGJyjru43AsT3rnVxmGG/Z3VwIABWpq2B1/iRkBSOhMqCId/tF3BOqfs0gfH6XBqMBxF8ZgZWPIzR43P7OnpRF6S+IJi58FdsHNYixPGCM9PuKwceM3DibGh2rOqN5PscQNnkJ8/kTjFCCQwDfZ5tPmlbU1Z+AD6dZoeM6eZDXh5L9uVm2pOqGum1wEE+R/ktgzsd8bXWweDALfDmZ8RKrMx5fACtJU+vKxcbwVs90xxkoacnZK6+xfzUZYACQTVB4aE08lXZVk8QvBOC19nFpOZ+mSziTBVVL4KE5xug3p3JBxg8qgJLJLgyEGb4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
